### ISSUE TITLE
Timeouts for environment variables and releases

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2258]
Hi,
suddenly, I'm getting timeouts here:
- Sometimes (!) when setting environment variables
- Always when pushing a new release. The release works fine afterwards though:

> ...
> remote: -----> Creating release...
> remote: Error deploying app release: timed out waiting for deployment completion
> To https://git.........com/myApp.git
> ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.........com/myApp.git'

**Comment by philiplb** [comment]
I'm still getting this timeouts. And currently, they seem to prevent a release of the app. It stays at the old state.
Also commands like
```bash
flynn run ls -la
```
are utterly slow. Slow as in about 1-2 minutes until I get a result.
Any clue?

**Comment by titanous** [comment]
@philiplb Debug info would be useful. Also, have you checked that there is enough disk space on the hosts?

**Comment by philiplb** [comment]
Hi,

yes, disk space is fine.
I always run into this pattern:

- I resetup the cluster from scratch
- I deploy (env-vars and git push), works fine
- I deploy again and run into timeouts

So more or less: I can deploy the application once and have to resetup the cluster afterwards.

Maybe it's interesting, that the slug-size is 110MB?

> Compiled slug size is 110M

Here is the debug info: https://gist.github.com/3892a19b52b7dfb0f9af

**Comment by titanous** [comment]
Yeah, sounds like large slug and repo sizes may be the cause.

**Comment by philiplb** [comment]
Just as a hint: This slug size is pretty normal for projects using Symfony2, Silex or any other bigger frameworks.

**Comment by titanous** [comment]
Yeah, thanks for reporting this. We consider it a bug and will investigate and fix.

**Comment by temujin9** [comment]
:+1: We are experiencing similar issues, across multiple frameworks.

**Comment by titanous** [comment]
I bumped the timeout in #2491

**Comment by temujin9** [comment]
Ah, cool. I'll redeploy, and we'll see if that quiets this down.

**Comment by titanous** [comment]
Note that after deploying the new version of Flynn you'll probably need to create new apps, existing apps might have the old timeout (though could be fixed with a bit of SQL).

**Comment by temujin9** [comment]
I'm probably gonna need that SQL: asking all my users to completely redeploy is problematic.

**Comment by titanous** [comment]
I'm AFK right now, I'll post it later today.

**Comment by titanous** [comment]
```text
flynn -a controller pg psql -- -c 'UPDATE apps SET deploy_timeout = 120'
```

This will work even if the cluster is not running the patch mentioned above, though new apps will require this modification in the database after creation to bump from the old 30 second default.

**Comment by titanous** [comment]
I believe this was fixed.

**Comment by philiplb** [comment]
Should be, yeah. Thx.

**Comment by philiplb** [comment]
With the version v20160314.0 on a freshly setup cluster I still get this. For example, (re-)deployment of env vars:
> timed out waiting for job events: map[web:map[up:1]]

**Comment by temujin9** [comment]
@titanous I still experience this on our clusters, regularly enough that I've just added a modification of your snippet to my push process. Tooling to modify this without resorting to psql would be good.

**Comment by lmars** [comment]
FYI I have a longer term fix in mind which is to move deployments to be regular jobs (part of #2620) and then there will no longer be a client timeout, the client will just wait for the deployment job to finish, and you will also be able to see the deployment log with something like `flynn log -t deploy`.

**Comment by temujin9** [comment]
That works too, and we've got the patch in place until that drops. Thanks!

**Comment by RobinDaugherty** [comment]
Just experienced this issue, and although initially we thought it was a timeout-related problem, in our case it wasn't. (The default timeout in the current release of Flynn is 120 seconds.)

The version of the app being deployed was broken in a subtle way, and the `web` process wasn't listening on the correct port.

After the slug finishes building, it launches a web process and waits for it to start listening on the correct port. It then completes the release. If the process never starts listening, the slug builder eventually just times out, there is no message that indicates the cause of the issue.

So if you landed on this issue because of a timeout, hopefully this helps you.

**Comment by aghasoroush** [comment]
@RobinDaugherty Exactly true. The problem was web process.

**Comment by hadifarnoud** [comment]
@RobinDaugherty how do you fix it? scale down or kill the job manually?

**Comment by RobinDaugherty** [comment]
@hadifarnoud the issue was that our app's web process wasn't opening a socket to listen for connections. The fix depends on your application.
