### ISSUE TITLE
Near zero-downtime production upgrades

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#3104]
We need a strategy to update production clusters safely to new Flynn versions. Currently the safest option is backup/restore, but this strategy does not allow writing to databases during an upgrade.

**Comment by IsNull** [comment]
I did try the in-place update several times over the last month (just for testing) on single node flynn clusters. It tends to break the cluster completely, usually resulting in discoverd not being available.
Reboots don't fix the issue, and `flynn-host fix --min-hosts=1` also failing with discoverd not being able to return host list.

Long story short, I think self diagnosis/healing should be addressed before this. A reboot (especially on a single node cluster) should be able to self diagnose and self heal in most cases. Such an ability would also improve the trust in Flynn, knowing it is able to recover from most situations. Downtime of 5 minutes is not optimal but not a big pain, but a broken cluster which needs manual intervention is a disaster for production environments.

**Comment by lmars** [comment]
@IsNull 

> I did try the in-place update several times over the last month (just for testing) on single node flynn clusters. It tends to break the cluster completely, usually resulting in discoverd not being available.

FYI I believe this was fixed during the migration to libcontainer (#3030, specifically [this change](https://github.com/flynn/flynn/pull/3030/commits/f754144c7c39d7e3289d83ff8659a75cc55aa660)). Previously every update would "resurrect" another discoverd job even though one was already running, causing issues.

If you continue to have the discoverd issue with in-place updates on releases since `v20160711.0` then let us know.

**Comment by n0daft** [comment]
We are still encountering the same issue with version v20170116.0p2.

see #4002

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
