### ISSUE TITLE
Problem creating backup of large volume cluster

### ISSUE THREAD

**Issue by holtgrewe** [flynn/flynn#3226]
Hi, we have a Flynn cluster with large databases. The backup process for the whole cluster stops at ~4GB. I think we might have hit a 32 bit integer overflow problem.

This is what it looks like on the cluster
```
$ flynn cluster backup --file=cluster.tar
Creating cluster backup...
3.90 GB 10.01 MB/s                                                                                                                    panic: runtime error: slice bounds out of range [recovered]
        panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x87b5d40, 0x19628010)
        /usr/local/go/src/runtime/panic.go:481 +0x326
github.com/flynn/flynn/pkg/shutdown.(*handler).exit(0x19671380, 0x0, 0x0, 0x0, 0x87b5d40, 0x19628010)
        /tmp/tmp.q0UeNuratJ/src/github.com/flynn/flynn/pkg/shutdown/handler.go:69 +0xdd
github.com/flynn/flynn/pkg/shutdown.Exit()
        /tmp/tmp.q0UeNuratJ/src/github.com/flynn/flynn/pkg/shutdown/handler.go:40 +0x59
panic(0x87b5d40, 0x19628010)
        /usr/local/go/src/runtime/panic.go:443 +0x3fd
archive/tar.(*Writer).Write(0x1970a900, 0x19ba8000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/archive/tar/writer.go:383 +0x88
io.copyBuffer(0xf77231b0, 0x1973b020, 0xf76e3168, 0x196296a8, 0x19ba8000, 0x8000, 0x8000, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/io/io.go:382 +0x229
io.Copy(0xf77231b0, 0x1973b020, 0xf76e3168, 0x196296a8, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:350 +0x53
github.com/flynn/flynn/pkg/backup.(*TarWriter).WriteCommandOutput(0x1973b020, 0xf76e7b40, 0x1966b260, 0x88a02c0, 0xf, 0x8891670, 0x8, 0x19764ff0, 0x0, 0x0)
        /tmp/tmp.q0UeNuratJ/src/github.com/flynn/flynn/pkg/backup/tar_writer.go:96 +0x904
github.com/flynn/flynn/pkg/backup.Run(0xf76e7b40, 0x1966b260, 0xf76e30e0, 0x1966b270, 0xf76e7c68, 0x1970c900, 0x0, 0x0)
        /tmp/tmp.q0UeNuratJ/src/github.com/flynn/flynn/pkg/backup/backup.go:36 +0x615
main.runClusterBackup(0x19821c50, 0x0, 0x0)
        /tmp/tmp.q0UeNuratJ/src/github.com/flynn/flynn/cli/cluster.go:406 +0x377
main.runCluster(0x19821c50, 0x0, 0x0)
        /tmp/tmp.q0UeNuratJ/src/github.com/flynn/flynn/cli/cluster.go:99 +0x2cd
main.runCommand(0xfffc077e, 0x7, 0x196df090, 0x2, 0x2, 0x0, 0x0)
        /tmp/tmp.q0UeNuratJ/src/github.com/flynn/flynn/cli/main.go:177 +0x43f
main.main()
        /tmp/tmp.q0UeNuratJ/src/github.com/flynn/flynn/cli/main.go:127 +0xb2d
```

Here is the ZFS volume size for further reference.

```
# zfs list
NAME                                                 USED  AVAIL  REFER  MOUNTPOINT
flynn-default                                       28.7G   305G    19K  none
flynn-default/1ebb8a8e-a72e-469e-bbc7-c814c5119db8  14.5G   305G  14.5G  /var/lib/flynn/volumes/zfs/mnt/1ebb8a8e-a72e-469e-bbc7-c814c5119db8
flynn-default/3cfdd0ed-20fe-4af7-96f3-e4e7ad167a8a   148K   305G   148K  /var/lib/flynn/volumes/zfs/mnt/3cfdd0ed-20fe-4af7-96f3-e4e7ad167a8a
flynn-default/5975b79c-8055-4033-a2a3-91325ffa9cc8  19.5K   305G  19.5K  /var/lib/flynn/volumes/zfs/mnt/5975b79c-8055-4033-a2a3-91325ffa9cc8
flynn-default/af2a50df-0fcf-490e-a2ac-e5125c9ee456  19.5K   305G  19.5K  /var/lib/flynn/volumes/zfs/mnt/af2a50df-0fcf-490e-a2ac-e5125c9ee456
flynn-default/c746bc58-3559-4e72-af6e-5468c6d355a4  14.2G   305G  14.2G  /var/lib/flynn/volumes/zfs/mnt/c746bc58-3559-4e72-af6e-5468c6d355a4
```

Is there anything else you need for a bug report?

**Comment by titanous** [comment]
Are you running the command on a 32-bit machine?

**Comment by holtgrewe** [comment]
We are seeing the following both on the client and on the server:

```
# uname -m
x86_64
```

We'd be happy to provide any further information for debugging.

Thanks!

**Comment by titanous** [comment]
What version of Flynn are you using? `flynn-host version`

**Comment by holtgrewe** [comment]
v20160721.2

**Comment by titanous** [comment]
Please run `file $(which flynn)` on the client and post the output.

**Comment by titanous** [comment]
Oh, and also post the output of `flynn version` from the client.

**Comment by holtgrewe** [comment]
OK, the reason was that we really had a 32bit binary.

The problem appears to be that `uname -sp` results in `"Linux unknown"` on the machine it ran on...

**Comment by holtgrewe** [comment]
(It works now with the 64 bit binary)

**Comment by titanous** [comment]
Okay, can you think of anything we can do about this? I can't think of anything that would be particularly useful, the panic is inside a few layers of the Go standard library and is too generic to detect reliably.

**Comment by holtgrewe** [comment]
Maybe defaulting to the 64 bit binary instead of the 32 bit download would be sensible? Is anyone still using 32 bit Linux in a server environment?

**Comment by titanous** [comment]
Yep, great idea. I'll set that up.

**Comment by titanous** [comment]
This is now fixed:

```text
$ curl -A "Linux unknown" -I https://dl.flynn.io/cli
HTTP/1.1 302 Moved Temporarily
Content-Type: text/plain; charset=utf-8
Connection: keep-alive
Cache-Control: no-cache
Date: Fri, 05 Aug 2016 15:24:37 GMT
Location: https://dl.flynn.io/tuf/targets/74ae613c42de4dfb4d6214c90ccb9c6361ba56892363b249ad4e9094c564e0f4b6a4f8b8735de13963a201b361b5afc33b563527da82f3bc36efd4510f0c1793.flynn-linux-amd64.gz
X-Cache: Miss from cloudfront
Via: 1.1 042ceabe1d85408fc3ac018cd255d256.cloudfront.net (CloudFront)
X-Amz-Cf-Id: 3OWc_DYzzrNp3oYAGCyw3b5Zj1whUktDJ53K6PeRRhjQu8JmxAU2qQ==
```


Thanks for reporting it!

**Comment by shasderias** [comment]
This issue might still exist for the Windows client.
                                                                                                                                                                                      ```
Creating cluster backup...
3.06 GB 3.62 MB/s                                                                                                                                                                               panic: runtime error: slice bounds out of range [recovered]
        panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0xb53b60, 0x11fb2010)
        /tmp/tmp.Sl1kpArwtL/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/panic.go:500 +0x331
github.com/flynn/flynn/pkg/shutdown.(*handler).exit(0x12035580, 0x0, 0x0, 0x0, 0xb53b60, 0x11fb2010)
        /tmp/tmp.Sl1kpArwtL/src/github.com/flynn/flynn/pkg/shutdown/handler.go:69 +0xdd
github.com/flynn/flynn/pkg/shutdown.Exit()
        /tmp/tmp.Sl1kpArwtL/src/github.com/flynn/flynn/pkg/shutdown/handler.go:40 +0x59
panic(0xb53b60, 0x11fb2010)
        /tmp/tmp.Sl1kpArwtL/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/panic.go:458 +0x40b
archive/tar.(*Writer).Write(0x121e0000, 0x122ba000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /tmp/tmp.Sl1kpArwtL/src/github.com/flynn/flynn/util/_toolchain/go/src/archive/tar/writer.go:369 +0x88
io.copyBuffer(0x12f7470, 0x1204ab80, 0x12f7f70, 0x11fb3540, 0x122ba000, 0x8000, 0x8000, 0x0, 0x0, 0x0, ...)
        /tmp/tmp.Sl1kpArwtL/src/github.com/flynn/flynn/util/_toolchain/go/src/io/io.go:392 +0x229
io.Copy(0x12f7470, 0x1204ab80, 0x12f7f70, 0x11fb3540, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.Sl1kpArwtL/src/github.com/flynn/flynn/util/_toolchain/go/src/io/io.go:360 +0x53
github.com/flynn/flynn/pkg/backup.(*TarWriter).WriteCommandOutput(0x1204ab80, 0x130cc80, 0x120481e0, 0xbdb9e2, 0xf, 0xbd6f85, 0x8, 0x11fa1420, 0x0, 0x0)
        /tmp/tmp.Sl1kpArwtL/src/github.com/flynn/flynn/pkg/backup/tar_writer.go:96 +0x6d4
github.com/flynn/flynn/pkg/backup.Run(0x130cc80, 0x120481e0, 0x12f7f90, 0x120481f0, 0x12f9b70, 0x120dc090, 0x0, 0x0)
        /tmp/tmp.Sl1kpArwtL/src/github.com/flynn/flynn/pkg/backup/backup.go:37 +0x6ee
main.runClusterBackup(0x121a4410, 0x0, 0x0)
        /tmp/tmp.Sl1kpArwtL/src/github.com/flynn/flynn/cli/cluster.go:429 +0x2cc
main.runCluster(0x121a4410, 0x0, 0x0)
        /tmp/tmp.Sl1kpArwtL/src/github.com/flynn/flynn/cli/cluster.go:122 +0x34e
main.runCommand(0x11fd40d0, 0x7, 0x120bbac0, 0x3, 0x4, 0x0, 0x0)
        /tmp/tmp.Sl1kpArwtL/src/github.com/flynn/flynn/cli/main.go:178 +0x47a
main.main()
        /tmp/tmp.Sl1kpArwtL/src/github.com/flynn/flynn/cli/main.go:128 +0x992
```

Flynn version: v20170113.0

```
C:\Users\shasderias\AppData\Roaming\flynn\bin>sigcheck flynn.exe

Sigcheck v2.54 - File version and signature viewer
Copyright (C) 2004-2016 Mark Russinovich
Sysinternals - www.sysinternals.com

C:\Users\shasderias\AppData\Roaming\flynn\bin\flynn.exe:
        Verified:       Unsigned
        Link date:      8:00 AM 01-Jan-70
        Publisher:      n/a
        Company:        n/a
        Description:    n/a
        Product:        n/a
        Prod version:   n/a
        File version:   n/a
        MachineType:    32-bit
```

Backup completes successfully on Linux (Ubuntu on Windows).

```
shasderias@SHASDERIAS:~$ uname -a
Linux SHASDERIAS 3.4.0+ #1 PREEMPT Thu Aug 1 17:06:05 CST 2013 x86_64 x86_64 x86_64 GNU/Linux
```
