### ISSUE TITLE
Update fails with tuf: failed to decode timestamp.json: expired at ...

### ISSUE THREAD

**Issue by nlsrchtr** [flynn/flynn#3408]
I was trying to update the cluster, because I was [stuck with an old release](https://github.com/flynn/flynn/issues/3407) and was hoping the get it fixed in a new version.

Following the documentation, I tried an in-place update with `flynn-host update` but got the following error: 

```
EROR[09-20|14:54:24] error updating TUF client err="tuf: failed to decode timestamp.json: expired at 2016-09-20 12:00:03 +0000 UTC"
14:54:24.079506 host.go:142: tuf: failed to decode timestamp.json: expired at 2016-09-20 12:00:03 +0000 UTC
```

Any suggestions on what I could do? I'll try to backup, update and restore the entire cluster now.

**Comment by nlsrchtr** [comment]
Also running `/tmp/install-flynn --clean` is leading to

```
ERROR: failed to run "./flynn-host download --repository https://dl.flynn.io/tuf --tuf-db /etc/flynn/tuf.db --config-dir /etc/flynn --bin-dir /usr/local/bin", exit status 1
```

So I don't see a way to update the installation. Does anyone have any suggestions?

**Comment by lmars** [comment]
@nlsrchtr I am investigating, this will be fixed shortly.

**Comment by lmars** [comment]
@nlsrchtr from the machine you are trying to run `flynn-host update` from, can you run the following and check the `expires` key?

```
$ curl https://dl.flynn.io/tuf/timestamp.json
```

When I run it from multiple locations, I get the correct expires of `2016-09-21T12:00:03Z`, I am unsure why you are receiving an old timestamp.

**Comment by nlsrchtr** [comment]
I'm getting this timestamp as well `2016-09-21T12:00:03Z`.

**Comment by lmars** [comment]
@nlsrchtr ok, please run the following which will attempt to run `flynn-host download` into a temporary directory (so we don't leave the host in an odd state):

```
$ sudo bash -c 'DIR=$(mktemp -d); trap "rm -rf ${DIR}" EXIT; FLYNN_VERSION=v20160918.1 flynn-host download --tuf-db "${DIR}/tuf.db" --config-dir "${DIR}" --bin-dir "${DIR}"'
```

Let's see if you get the same error.

**Comment by nlsrchtr** [comment]
Thanks for your help! I had to run it on the second node, because on the first `flynn-host` isn't available anymore, but got the same error:

```
root@flynn-02:~# sudo bash -c 'DIR=$(mktemp -d); trap "rm -rf ${DIR}" EXIT; FLYNN_VERSION=v20160918.1 flynn-host download --tuf-db "${DIR}/tuf.db" --config-dir "${DIR}" --bin-dir "${DIR}"'
INFO[09-20|16:09:28] initializing TUF client
EROR[09-20|16:09:29] error updating TUF client err="tuf: failed to decode timestamp.json: expired at 2016-09-20 12:00:03 +0000 UTC"
16:09:29.114722 host.go:142: tuf: failed to decode timestamp.json: expired at 2016-09-20 12:00:03 +0000 UTC
```
Maybe Amazon is delivering an older version of the version? Is `curl -H 'Cache-Control: no-cache' https://dl.flynn.io/tuf/timestamp.json` maybe a solution?

**Comment by titanous** [comment]
I've pushed a CF invalidation for the URL in an attempt to unclog the tubes, it might take up to 20 minutes, we're going to change how we do caching headers soon so that this can't happen in the future (#2675).

**Comment by nlsrchtr** [comment]
Sorry to bother again. The issue is still the same - I'll check again tomorrow.

**Comment by nlsrchtr** [comment]
It works today. Thanks for your help! I'll reinstall the cluster with the newer version now.
